version: '3.8'
services:
  api.pharmacy-nginx:
    image: nginx:alpine3.17
    restart: always
    depends_on:
      - pharmacy-db
      - api.pharmacy
    container_name: api.pharmacy-nginx
    ports:
      - 81:80
      - 444:443
    volumes:
      - ./api/:/var/www
      - ./docker/:/etc/nginx/conf.d
    networks:
      - pharmacy-networks

  pharmacy-db:
    image: mysql:8.0.33
    restart: unless-stopped
    container_name: pharmacy-db
    env_file:
      - ./api/.env
    environment:
      - MYSQL_USER=pharmacydb
      - MYSQL_PASSWORD=pharmacydb
      - MYSQL_DATABASE=pharmacydb
      - MYSQL_ROOT_PASSWORD=pharmacydb
    ports:
      - 3306:3306
    volumes:
      - pharmacy-db:/var/lib/mysql
    networks:
      - pharmacy-networks

  api.pharmacy:
    build:
      context: ./api
      dockerfile: lv.Dockerfile
    container_name: api.pharmacy
    working_dir: /var/www
    ports:
      - 9000:9000
    networks:
      - pharmacy-networks
    volumes:
      - ./api/:/var/www

  vue.pharmacy:
    build:
      context: ./vue-app
      dockerfile: vue.Dockerfile
    container_name: vue.pharmacy
    working_dir: /app
    restart: always
    networks:
      - pharmacy-networks
    ports:
      - 8080:8080
    volumes:
      - ./vue-app/:/app

volumes:
  pharmacy-db:

networks:
  pharmacy-networks:
    driver: bridge
